[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"
  # Opcionalmente especifica:
  # node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200